apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-asia-d2
spec:
  selector:
      matchLabels:
        app: demo-asia-d2
  replicas: 5
  strategy:
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: demo-asia-d2
        date: 'Timestamp'
    spec:
      containers:
      - name: demo-asia-d2
        image: agenacr.azurecr.io/demo-asia-d2:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-asia-d2
spec:
  selector:
    app: demo-asia-d2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-demo
spec:
  secretName: tls-secret-demo
  dnsNames:
  - demo.online.agenarisk.com
  renewBefore: 360h
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - demo.online.agenarisk.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-demo-api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
  - hosts:
    - demo.online.agenarisk.com
    secretName: tls-secret-demo
  rules:
  - host: demo.online.agenarisk.com
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-asia-d2
          servicePort: 80
